# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\src\python\sub-decorator\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from re import L
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

from Ui_SubTitleDialog import Ui_DialogSubTitle

class Ui_MainWindow(object):
    def __init__(self) :
        super().__init__()
        return
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.reportEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.reportEdit.setObjectName("reportEdit")
        self.gridLayout.addWidget(self.reportEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu1_File = QtWidgets.QMenu(self.menubar)
        self.menu1_File.setObjectName("menu")
        self.menu3_Subtitle = QtWidgets.QMenu(self.menubar)
        self.menu3_Subtitle.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MenuExit = QtWidgets.QAction(MainWindow)
        self.MenuExit.setObjectName("MenuExit")
        self.MenuGenST = QtWidgets.QAction(MainWindow)
        self.MenuGenST.setObjectName("MenuGenST")
        self.menu1_File.addSeparator()
        self.menu1_File.addAction(self.MenuExit)
        self.menu3_Subtitle.addAction(self.MenuGenST)
        self.menubar.addAction(self.menu1_File.menuAction())
        self.menubar.addAction(self.menu3_Subtitle.menuAction())

        self.retranslateUi(MainWindow)
        self.MenuExit.triggered.connect(MainWindow.close)
        
        self.MenuGenST.triggered.connect(self.generateBigSubTitle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu1_File.setTitle(_translate("MainWindow", "文件"))
        self.menu3_Subtitle.setTitle(_translate("MainWindow", "字幕"))
        self.MenuExit.setText(_translate("MainWindow", "退出(&E)"))
        self.MenuGenST.setText(_translate("MainWindow", "Big字幕生成(&G)"))

    def generateBigSubTitle(self) :
        #QtWidgets.QMessageBox.information(None, '消息', str(type(self)), QtWidgets.QMessageBox.Ok)
        #DlgSTParam = Ui_DialogSubTitle()
        #result = DlgSTParam.exec_()
        DlgSTParam = QDialog()
        DlgSTParam.setWindowFlag(QtCore.Qt.WindowMinMaxButtonsHint)
        ui = Ui_DialogSubTitle()
        assert(isinstance(self, Ui_MainWindow))
        
        ui.setupUi(DlgSTParam)
        if DlgSTParam.exec() :
            pass
        return

